#####  Configuration file for the chosen optical system

infos:
    system name: HYACAMEO

system architecture:
    system type: SD-CASSI
    propagation type: simca
    focal lens: 200000
    dispersive element:
    #Â dispersive element caracteristics
        type: prism        # name of the dispersive element
        A: 15              # apex angle of the prism in degrees      (only used if type == 'prism')   -- in degrees
        m: 1               # grating order to consider         (only used if type == 'grating')       -- no units
        G: 30             # grating density                   (only used if type == 'grating')       -- in lines/mm
        delta alpha c: 0
        delta beta c: 0
        wavelength center: 550  # central wavelength -- in nm
detector:
    number of pixels along X: 201                  # number of pixels along X axis -- no units
    number of pixels along Y: 201                  # number of pixels along Y axis -- no units
    pixel size along X: 40                             # pixel size along X       -- in um
    pixel size along Y: 40                              # pixel size along Y       -- in um
coded aperture:
    number of pixels along X: 253                  # number of pixels along X axis -- no units
    number of pixels along Y: 201                  # number of pixels along Y axis -- no units
    pixel size along X: 55                              # pixel size along X       -- in um
    pixel size along Y: 55                              # pixel size along Y       -- in um

spectral range:
    wavelength min: 450     # minimum wavelength -- in nm
    wavelength max: 640      # maximum wavelength -- in nm
    number of spectral samples: 50
